version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: zyon_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zyon_db
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
      
volumes:
  .postgres-data: